// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmMAX2VcENOmop34xQwk4nRJ4mimmzYjA',
    appId: '1:568140400001:web:314318728031323b5e9480',
    messagingSenderId: '568140400001',
    projectId: 'fitlabs-cd73c',
    authDomain: 'fitlabs-cd73c.firebaseapp.com',
    storageBucket: 'fitlabs-cd73c.firebasestorage.app',
    measurementId: 'G-9YYB82E15W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-X42BhAtWHBkwXgIxcBbnkwE_AFINJys',
    appId: '1:568140400001:android:388aa5fed188aa105e9480',
    messagingSenderId: '568140400001',
    projectId: 'fitlabs-cd73c',
    storageBucket: 'fitlabs-cd73c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrb-4CU-TI3XiLAfqKAGAPEitcGLqpYg',
    appId: '1:568140400001:ios:63cec9b7a0fd94eb5e9480',
    messagingSenderId: '568140400001',
    projectId: 'fitlabs-cd73c',
    storageBucket: 'fitlabs-cd73c.firebasestorage.app',
    iosBundleId: 'com.example.pantallasFitlabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYrb-4CU-TI3XiLAfqKAGAPEitcGLqpYg',
    appId: '1:568140400001:ios:63cec9b7a0fd94eb5e9480',
    messagingSenderId: '568140400001',
    projectId: 'fitlabs-cd73c',
    storageBucket: 'fitlabs-cd73c.firebasestorage.app',
    iosBundleId: 'com.example.pantallasFitlabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmMAX2VcENOmop34xQwk4nRJ4mimmzYjA',
    appId: '1:568140400001:web:704c4001ec2c62325e9480',
    messagingSenderId: '568140400001',
    projectId: 'fitlabs-cd73c',
    authDomain: 'fitlabs-cd73c.firebaseapp.com',
    storageBucket: 'fitlabs-cd73c.firebasestorage.app',
    measurementId: 'G-3MCRVEF9CB',
  );
}
